[program:edm-prepare]
environment=PROC_NAME="%(program_name)s"
command=/opt/supervisor-scripts/edm-prepare.sh
autostart=false
autorestart=false
startsecs=1
stdout_logfile=/dev/stdout
redirect_stderr=true
stdout_logfile_maxbytes=0
